name: Run My Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Script
        run: ./myscript.sh

      - name: Diagnostic Info
        run: |
          ls -l
          file ./myscript.sh
          cat ./myscript.sh
